Documentation:
  Enabled: false

LineLength:
  Enabled: false

AssignmentInCondition:
  Enabled: false

MethodLength:
  Max: 50

AllCops:
  Excludes:
    - db/**/*
    - config/initializers/simple_form_bootstrap.rb
