default: &default
  host: localhost
  port: 6379

development:
  <<: *default
  db: gamification_development

test:
  <<: *default
  db: gamification_test

production:
  <<: *default
  db: gamification_production
