# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e1c70b1e39abb30468101b5db19cb98b664ad4af239235c9325c48082b7faf7612ec952a41e34e4146607f0a39bf21559ab5183a5e66f09d67167401201137b

test:
  secret_key_base: b1da220a241e3ccfa404d56066274aac727ad8ea14b76c509d0a6aaaf3f95299947db2108450f1f77e2e5c088eff8b42e005776b8536f0b274fd3457928ed588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
